# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hard.Dance
email: info@hard.dance
description: "Coming soon"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hard-dance.netlify.app" # the base hostname & protocol for your site, e.g. http://example.com
lang: "en-US"
repository: "https://github.com/FlyersPh9/hard-dance"

permalink: /:categories/:title:output_ext

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compact # possible values: nested expanded compact compressed

incremental: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

admins:
  - name: Eugene Berzin
    alias: Treachery
    position: Owner
    location: ðŸ‡ªðŸ‡¸
    email: eugene@hard.dance
    website: https://djtreachery.com
    socials:
      - service: Facebook
        url: https://www.facebook.com/djtreachery/
      - service: Instagram
        url: https://www.instagram.com/djtreachery/
      - service: Discord
        url: https://discordapp.com/users/djtreachery
      - service: Spotify
        url: https://open.spotify.com/artist/5b4RTDc2Q3bNHmv0L8ZPlj
      - service: YouTube
        url: https://www.youtube.com/channel/UCZFth4RG7KqOig5MAsmft3g
      - service: Soundcloud
        url: http://www.soundcloud.com/djtreachery
      - service: Apple Music
        url: https://music.apple.com/us/artist/treachery/300126894
  - name: Jon Graft
    alias: Johnny Hardstyle
    position: Web designer & developer
    location: ðŸ‡ºðŸ‡¸
    email: me@jongraft.design
    website: https://jongraft.design
    socials:
      - service: Facebook
        url: https://www.facebook.com/FlyersPh9
      - service: Twitter
        url: https://www.twitter.com/JonGraftDesign
      - service: GitHub
        url: https://github.com/FlyersPh9
      - service: Discord
        url: https://discordapp.com/users/flyersph9

event-hosts:
  - name: A.L.E.X. Events
    url: https://www.alex-events.net
    facebook: https://www.facebook.com/Official.alexevents/
  - name: Airbeat One
    url: https://airbeat-one.de
    facebook: https://www.facebook.com/airbeatone/
  - name: Army of Hardcore USA
    facebook: https://www.facebook.com/armyofhardcore.usa/
  - name: Art of Dance
    url: https://www.artofdance.nl
    facebook: https://www.facebook.com/artofdanceofficial/
  - name: b2s
    url: https://www.b2s.nl
    facebook: https://www.facebook.com/officialb2s/
  - name: Bass Events
    url: https://www.bassevents.be
    facebook: https://www.facebook.com/bassevents/
  - name: Basscon
    facebook: https://www.facebook.com/bassconmassive/
  - name: BKJN events
    facebook: https://www.facebook.com/BKJNevents/
  - name: Devastator Events
    url: https://devastatorevents.cz
    facebook: https://www.facebook.com/Devastator.events/
  - name: Dreamfields Mexico
    url: https://dreamfields.mx
    facebook: https://www.facebook.com/dreamfieldsmexico/
  - name: Dropzone
    url: https://dropzonefest.com
    facebook: https://www.facebook.com/dropzonefest/
  - name: East Coast Hard Dance
    url: https://eastcoastharddance.com
    facebook: https://www.facebook.com/EastCoastHardDance/
  - name: Fatality
    facebook: https://www.facebook.com/fatalityevent/
  - name: Gearbox Digital
    url: https://gearboxdigital.com
    facebook: https://www.facebook.com/GearboxDigital/
  - name: Hardice
    facebook: https://www.facebook.com/hardice.ch/
  - name: Hardstyle Arena
    facebook: https://www.facebook.com/FreshHardstyleArena/
  - name: Harmony of Hardcore
    url: https://www.harmonyofhardcore.nl
    facebook: https://www.facebook.com/HOHfestival/
  - name: Hellfire
    url: https://hell-fire.co.uk
    facebook: https://www.facebook.com/Hellfireshow/
  - name: I AM HARDSTYLE
    url: https://iamhardstyle.com
    facebook: https://www.facebook.com/iamhardstyleofficial/
  - name: Intents Festival
    url: https://www.intentsfestival.nl
    facebook: https://www.facebook.com/intentsfestival/
  - name: Matrixx
    url: https://www.matrixx.nl
    facebook: https://www.facebook.com/MatrixxEvents/
  - name: Multigroove
    url: https://multigroove.com
    facebook: https://www.facebook.com/multigroove/
  - name: Musical Madness
    url: https://www.musical-madness.de
    facebook: https://www.facebook.com/musicalmadnessofficial/
  - name: Project Hardstyle CH
    facebook: https://www.facebook.com/ProjectHardstyleCH/
  - name: Q-dance
    url: https://www.q-dance.com
    facebook: https://www.facebook.com/Qdance/
  - name: Shockerz
    url: https://shockerz.nl
    facebook: https://www.facebook.com/shockerzofficial/
  - name: Tomorrowland
    url: https://www.tomorrowland.com
    facebook: https://www.facebook.com/tomorrowland/
  - name: Twisted Events
    facebook: https://www.facebook.com/twisted.events.official/
  - name: WhiteNorat.
    facebook: https://www.facebook.com/Whitenoratevents/

event-types:
  - Festival
  - Arena
  - Club
  - Underground

friends:
  - title: /r/hardstyle
    subtitle: Reddit
    url: https://www.reddit.com/r/hardstyle/
  - title: Hard Dance Release Radar
    subtitle: Spotify
    url: https://www.hdrr.info
