title: Hard.Dance
email: info@hard.dance
description: "The #1 aggregate of all things hard dance related. Join us and become a part of our digital tribe."
baseurl: ""
url: "https://hard.dance"
lang: "en-US"
repository: "https://github.com/Hard-Dance/hard-dance"
privacy-policy: "https://www.iubenda.com/privacy-policy/61434249"
cookie-policy: "https://www.iubenda.com/privacy-policy/61434249/cookie-policy"

permalink: /:categories/:title:output_ext

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-dotenv

sass:
  sass_dir: _sass
  style: compressed

incremental: true

facebook:
  app_id: 2501572726592422
  publisher: "https://www.facebook.com/harddotdance"
  admins: 10161721660276983

admins:
  - name: Eugene Berzin
    alias: Treachery
    position: Owner
    location: ðŸ‡ªðŸ‡¸
    email: eugene@hard.dance
    website: https://djtreachery.com
    socials:
      - service: Facebook
        url: https://www.facebook.com/djtreachery
      - service: Instagram
        url: https://www.instagram.com/djtreachery
      - service: Discord
        url: https://discordapp.com/users/djtreachery
      - service: Spotify
        url: https://open.spotify.com/artist/5b4RTDc2Q3bNHmv0L8ZPlj
      - service: YouTube
        url: https://www.youtube.com/channel/UCZFth4RG7KqOig5MAsmft3g
      - service: Soundcloud
        url: http://www.soundcloud.com/djtreachery
      - service: Apple Music
        url: https://music.apple.com/us/artist/treachery/300126894
  - name: Jon Graft
    alias: Johnny Hardstyle
    position: Owner
    location: ðŸ‡ºðŸ‡¸
    email: me@jongraft.design
    website: https://jongraft.design
    socials:
      - service: Facebook
        url: https://www.facebook.com/FlyersPh9
      - service: Twitter
        url: https://www.twitter.com/JonGraftDesign
      - service: GitHub
        url: https://github.com/FlyersPh9
      - service: Discord
        url: https://discordapp.com/users/flyersph9

event-hosts:
  - name: A.L.E.X. Events
    url: https://www.alex-events.net
    facebook: https://www.facebook.com/Official.alexevents
  - name: Airbeat One
    url: https://airbeat-one.de
    facebook: https://www.facebook.com/airbeatone
  - name: Army of Hardcore USA
    facebook: https://www.facebook.com/armyofhardcore.usa
  - name: Art of Dance
    url: https://www.artofdance.nl
    facebook: https://www.facebook.com/artofdanceofficial
  - name: b2s
    url: https://www.b2s.nl
    facebook: https://www.facebook.com/officialb2s
  - name: Bass Events
    url: https://www.bassevents.be
    facebook: https://www.facebook.com/bassevents
  - name: Basscon
    url: https://www.bassconmassive.com
    facebook: https://www.facebook.com/bassconmassive
  - name: BKJN events
    url: https://bkjn.nl
    facebook: https://www.facebook.com/BKJNevents
  - name: Chemistry Event
    facebook: https://www.facebook.com/profile.php?id=100088066611103
  - name: Devastator Events
    url: https://devastatorevents.cz
    facebook: https://www.facebook.com/Devastator.events
  - name: Dreamfields Mexico
    url: https://dreamfields.mx
    facebook: https://www.facebook.com/dreamfieldsmexico
  - name: Dropzone
    url: https://dropzonefest.com
    facebook: https://www.facebook.com/dropzonefest
  - name: East Coast Hard Dance
    url: https://eastcoastharddance.com
    facebook: https://www.facebook.com/EastCoastHardDance
  - name: Electric Love
    url: https://www.electriclove.at
    facebook: https://www.facebook.com/electriclovefestival
  - name: Fatality
    facebook: https://www.facebook.com/fatalityevent
  - name: Gearbox Digital
    url: https://gearboxdigital.com
    facebook: https://www.facebook.com/GearboxDigital
  - name: Hard Dance NYC
    facebook: https://www.facebook.com/hard.dance.nyc
  - name: HARDFEST
    url: https://www.hardfest.nl
    facebook: https://www.facebook.com/hardfest.nl
  - name: Hardice
    facebook: https://www.facebook.com/hardice.ch
  - name: Hardstyle Arena
    facebook: https://www.facebook.com/FreshHardstyleArena
  - name: Harmony of Hardcore
    url: https://www.harmonyofhardcore.nl
    facebook: https://www.facebook.com/HOHfestival
  - name: Heart of Hard
    url: https://heartofhard.cz
    facebook: https://www.facebook.com/heartofhard
  - name: Hellfire
    url: https://hell-fire.co.uk
    facebook: https://www.facebook.com/Hellfireshow
  - name: High Energy Events
    url: https://www.highenergyevents.nl
    facebook: https://www.facebook.com/officialhighenergyevents
  - name: I AM HARDSTYLE
    url: https://iamhardstyle.com
    facebook: https://www.facebook.com/iamhardstyleofficial
  - name: Infinity Festival
    url: https://infinity-festival.nl
    facebook: https://www.facebook.com/profile.php?id=100091682835269
  - name: Intents Festival
    url: https://www.intentsfestival.nl
    facebook: https://www.facebook.com/intentsfestival
  - name: Let it out events
    facebook: https://www.facebook.com/profile.php?id=100089362122143
  - name: Masters of Hardcore
    url: https://www.mastersofhardcore.com
    facebook: https://www.facebook.com/officialMOH
  - name: Matrixx
    url: https://www.matrixx.nl
    facebook: https://www.facebook.com/MatrixxEvents
  - name: Multigroove
    url: https://multigroove.com
    facebook: https://www.facebook.com/multigroove
  - name: Musical Madness
    url: https://www.musical-madness.de
    facebook: https://www.facebook.com/musicalmadnessofficial
  - name: Mysteryland
    url: https://www.mysteryland.nl
    facebook: https://www.facebook.com/Mysteryland
  - name: Outlaw Events
    url: https://www.outlawevents.nl
    facebook: https://www.facebook.com/outlawevents.nl
  - name: Overloud Events
    facebook: https://www.facebook.com/ovldevents
  - name: Parookaville
    url: https://www.parookaville.com
    facebook: https://www.facebook.com/parookaville
  - name: Project Hardstyle CH
    facebook: https://www.facebook.com/ProjectHardstyleCH
  - name: Q-dance
    url: https://www.q-dance.com
    facebook: https://www.facebook.com/Qdance
  - name: Ravefield
    url: https://ravefield.com
    facebook: https://www.facebook.com/ravefield.official
  - name: Ravingz Bass
    facebook: https://www.facebook.com/ravingzbass
  - name: Rawfare
    url: https://www.rawfare.nl
    facebook: https://www.facebook.com/RawfareOfficial
  - name: Recharged
    facebook: https://www.facebook.com/rechargedevent
  - name: Reminder
    url: https://reminderhardstyleclassics.com
    facebook: https://www.facebook.com/hardstyleclassics2006till2011
  - name: Ruggengraatjes
    facebook: https://www.facebook.com/profile.php?id=100089611314203
  - name: MYK Events
    url: https://www.myk-events.nl
    facebook: https://www.facebook.com/RevengeWHMH
  - name: Shockerz
    url: https://shockerz.nl
    facebook: https://www.facebook.com/shockerzofficial
  - name: State of Bass
    facebook: https://www.facebook.com/profile.php?id=100063544059838
  - name: Supersized Kingsday
    facebook: https://www.facebook.com/supersizedkingsdayfestival
  - name: The Hardest
    facebook: https://www.facebook.com/profile.php?id=100089439726875
  - name: Thunderdome
    url: https://www.thunderdome.com
    facebook: https://www.facebook.com/ThunderdomeIsYou
  - name: Tomorrowland
    url: https://www.tomorrowland.com
    facebook: https://www.facebook.com/tomorrowland
  - name: Twisted Events
    facebook: https://www.facebook.com/twisted.events.official
  - name: WhiteNorat.
    facebook: https://www.facebook.com/Whitenoratevents

friends:
  - title: /r/hardstyle
    subtitle: Reddit
    url: https://www.reddit.com/r/hardstyle
  - title: Hard Dance Release Radar
    subtitle: Spotify
    url: https://www.hdrr.info
  - title: HarderState
    subtitle: Forum
    url: https://harderstate.com

google_maps_api_key: $GOOGLE_MAPS_API_KEY
